eol = true

name = "kotlin"
title = "Kotlin Coroutine"
intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/drivers/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
]

toc_landing_pages = [
    "/fundamentals/connection",
    "/fundamentals/crud",
    "/fundamentals/builders",
    "/usage-examples",
    "/api-documentation",
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
driver = "kotlin"
driver-short = "Kotlin driver"
driver-long = "MongoDB Kotlin Driver"
version = "4.10"
full-version = "{+version+}.1"
language = "Kotlin"
mdb-server = "MongoDB server"
kotlin-docs = "https://kotlinlang.org"

package-name-org = "mongodb-org"
api = "https://mongodb.github.io/mongo-java-driver/{+version+}"
stable-api = "Stable API"
mongocrypt-version = "1.8.0"
nettyVersion = "io.netty:netty-all:4.1.79.Final"
snappyVersion = "org.xerial.snappy:snappy-java:1.1.8.4"
zstdVersion = "com.github.luben:zstd-jni:1.5.5-2"
logbackVersion = "1.2.11"
log4j2Version = "2.17.1"
serializationVersion = "1.5.1"
bsonVersion = "4.10.1"
current-url = "https://www.mongodb.com/docs/drivers/kotlin/coroutine/current/"

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer supported. View the `current documentation <{+current-url+}>`__ to learn how to `install a newer version of the {+driver-short+} <{+current-url+}/quick-start/#add-mongodb-as-a-dependency>`__.\
    """
