name: Kotlin Example Tests

on:
  pull_request:
    paths:
      - 'examples/**'

defaults:
  run:
    working-directory: examples # The working directory path

jobs:
  build:
    name: Run Kotlin Example Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Run Kotlin tests
        run: ./gradlew test --stacktrace --info
        env: 
          CI: true
          CONNECTION_URI: ${{ secrets.CONNECTION_URI }}