name: Kotlin Example Tests

on:
  pull_request:
    paths:
      - 'examples/**'

defaults:
  run:
    working-directory: examples # The working directory path

jobs:
  build:
    name: Run Kotlin Example Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
    
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          # mongodb-username: supercharge
          # mongodb-password: secret
          # mongodb-db: supercharge
  
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
  
      - name: Set up Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
  
      - run: ./gradlew build
  
      - run: ./gradlew test --stacktrace --info
        env: 
          CI: true
          # CONNECTION_STRING: mongodb://supercharge:secret@localhost:27017/supercharge?authSource=admin
          CONNECTION_STRING: mongodb://localhost:27017
